<a href="https://colab.research.google.com/github/Hellionember/torch/blob/main/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import torch
import numpy as np

# 1. Создаем обычный массив в NumPy
np_array = np.array([[1, 2], [3, 4]])

# 2. Конвертируем его в тензор PyTorch
py_tensor = torch.from_numpy(np_array)

# 3. Или создаем тензор напрямую (например, заполненный случайными числами)
random_tensor = torch.rand(size=(2, 3)) # Матрица 2x3

print("NumPy array:\n", np_array)
print("PyTorch tensor:\n", py_tensor)
print("Random tensor:\n", random_tensor)

NumPy array:
 [[1 2]
 [3 4]]
PyTorch tensor:
 tensor([[1, 2],
        [3, 4]])
Random tensor:
 tensor([[0.5462, 0.0581, 0.8791],
        [0.1365, 0.2440, 0.0882]])


In [41]:
tenz_zer = torch.zeros(size=[3, 4])
print(tenz_zer)
print(tenz_zer.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])


In [42]:
# Создадим тензор 1D с числами от 0 до 11 (всего 12 элементов)
x = torch.arange(12)
print(f"Original x shape: {x.shape}")

# Превратим его в 2D матрицу 3х4
matrix_x = x.view(3, 4)
print(f'Matrix shape: {matrix_x.shape}')

Original x shape: torch.Size([12])
Matrix shape: torch.Size([3, 4])


In [43]:
print(x, matrix_x, sep='\n')

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [44]:
A = torch.ones((2, 3))
B = torch.ones((3, 5))

C = A @ B
print(C.shape, A, B, sep='\n')

torch.Size([2, 5])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [45]:
#tenz_zer = tenz_zer.T(1)
print(tenz_zer.reshape([-1]))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [46]:
print(list(tenz_zer.size()))

[3, 4]


In [47]:
# Исходные данные (например, x = площадь квартиры, ideal_y = реальная цена)
x = torch.tensor(2.0)
ideal_y = torch.tensor(10.0)

# Наши параметры, которые сеть будет обучать. Задаем им requires_grad=True!
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [49]:
# 1. Прямой проход (Forward pass) - сеть делает предсказание
predictet_y = w * x + B

# 2. Считаем ошибку (Loss) - насколько мы далеки от идеала (Используем MSE - квадрат ошибки)
loss = (predictet_y - ideal_y)**2

# УСРЕДНЯЕМ ОШИБКУ до одного числа (скаляра) перед backward
loss = loss.mean()

# 3. МАГИЯ PYTORCH: считаем градиенты (Backpropagation)
loss.backward()

# Теперь мы можем посмотреть, куда нам нужно менять w и b
print('Градиент для w:', w.grad)
print('Градиент для b:', b.grad)

Градиент для w: tensor(-28.0000)
Градиент для b: None
